spring:
  h2:
    console:
      enabled: true
      path: /catdb-console
  datasource:
    url: jdbc:h2:mem:catdb
    username: cat
    password: supercat
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

  thymeleaf:
    suffix: .html
